try {
    alert("Lists created successfully..!! Please check console message..!!")
    console.log("Successfully generated lists..!!")
} catch (error) {
    console.log("Some error has occured: " + error.message);
}